### PR TITLE
BP-1061 - Fix multiple refund transactions for AfterPay

### PR DESCRIPTION
**Pull request by serpentscode**

### CODE REVIEW

**Comment by vladislav-padalka-hys** [comment]
@serpentscode 
I've tested your pull request https://github.com/buckaroo-it/WooCommerce/pull/5 you did and see that it doesn't work for me completely

Yeah there is one refund request will be made, BUT it's failed due to difference between total and sum of articles

Example transaction is https://plaza.buckaroo.nl/Transaction/Transactions/Details?transactionKey=0DB4D14CFD174BBEAED37C659C75FA68

Video with all actions is : https://drive.google.com/file/d/1SLehdK2lp-c6mm1BcGB_g2-cDoCT25pq/view?usp=sharing

Please check

**Comment by serpentscode** [comment]
> @serpentscode I've tested your pull request #5 you did and see that it doesn't work for me completely
> 
> Yeah there is one refund request will be made, BUT it's failed due to difference between total and sum of articles
> 
> Example transaction is https://plaza.buckaroo.nl/Transaction/Transactions/Details?transactionKey=0DB4D14CFD174BBEAED37C659C75FA68
> 
> Video with all actions is : https://drive.google.com/file/d/1SLehdK2lp-c6mm1BcGB_g2-cDoCT25pq/view?usp=sharing
> 
> Please check



> @serpentscode I've tested your pull request #5 you did and see that it doesn't work for me completely
> 
> Yeah there is one refund request will be made, BUT it's failed due to difference between total and sum of articles
> 
> Example transaction is https://plaza.buckaroo.nl/Transaction/Transactions/Details?transactionKey=0DB4D14CFD174BBEAED37C659C75FA68
> 
> Video with all actions is : https://drive.google.com/file/d/1SLehdK2lp-c6mm1BcGB_g2-cDoCT25pq/view?usp=sharing
> 
> Please check

Checking, thanks!

**Comment by vladislav-padalka-hys** [comment]
@serpentscode  

it still doesn't work as expected

now we have 1 refund, no error, but refund amount simply less is than expected
see my demo video and screenshot

https://drive.google.com/file/d/1AmyIhYkpFLF1_zcTN3HaEA-9U9mSI0Mh/view?usp=sharing

transaction https://plaza.buckaroo.nl/Transaction/Transactions/Details?transactionKey=4276F40F8CE94C839CE4209D47CA98AF

**Comment by serpentscode** [comment]
@vladislav-padalka-hys , thanks for your review.

That's right, but this issue is assigned to another ticket (BP-1166), that I'm currently working on it. A serparate fix should come later today.

Payment fee isn't refunded and the amount is less that expected.

**Review by vladislav-padalka-hys — APPROVED** [review]

**Pull request merged**
